package pt.isec.g45.tp.utils;

public enum CodigosTCP {
    EDITAR_DADOS_REGISTO,
    CONSULTA_ESPETACULOS,
    SELECT_ESPETACULO,
    SELECT_AVAILABLE_SITS_FROM_SHOW,
    TRANSFERE_DB,
    GET_NOT_PAYED_RESERVATIONS,
    GET_PAYED_RESERVATION,
    DELETE_NOT_PAYED_RESERVATION,
    GET_FILTERED_SHOW,
    CONSULTA_ESPETACULO,
    MAKE_RESERVATION,
    PAY_RESERVATION,
    LOGOUT,
    ASK_FOR_SITS,
    DELETE_SHOW,
    INSERT_SHOW,
    RESERVE_SITS
}
